### ISSUE TITLE
Duplicate declaration "_JSXStyle"

### ISSUE THREAD

**Issue by BafS** [giuseppeg/styled-jsx-plugin-postcss#1]
Hi,

I followed your readme but unfortunately I'm not able to run your plugin with next.js 4

I have this error

```bash
Module build failed: TypeError: unknown: Duplicate declaration "_JSXStyle"
  2 | import _JSXStyle from 'styled-jsx/style';
  3 | import React from 'react';
> 4 | import _JSXStyle from 'styled-jsx/style';
    |        ^
  5 | import Link from 'next/dist/lib/link.js';
  6 | import Button from '../components/Button';
```

Thanks in advance !

**Comment by giuseppeg** [comment]
@BafS do you mind putting together a sample repo so that I can take a look?

**Comment by BafS** [comment]
@giuseppeg I updated styled-jsx with the last version and next.js 4.1.0 and I'm not sure exactly why but it works. Thanks for this plugin !
