### ISSUE TITLE
Changes in imported files aren't picked up without cache clearing and server restart

### ISSUE THREAD

**Issue by jgubman** [giuseppeg/styled-jsx-plugin-postcss#14]
Following up on:
https://github.com/zeit/styled-jsx/issues/254#issuecomment-350449414

Any chance we'll see any movement on the caching issues around changes to files that are loaded via @import not being picked up w/o a full cache clear and server restart? It's a major stumbling block especially as new devs join our team and tweak a css file and then wonder for an hour why their changes aren't being picked up.

**Comment by kennedyrose** [comment]
Same here. We're trying to build a design system around styled-jsx but I'm not sure it's possible because of this.

**Comment by jgubman** [comment]
FWIW, I've hacked around this bug w/ the following snippet in my server.js:

```
  chokidar.watch('./static/variables.css').on('change', event => {
    app.close().then(() => {
      server.close()
      exec('rm -rf ./node_modules/.cache', (err, stdout, stderr) => {
        startApp()
      })
    })
  })
```

It's ugly, but better than having to remember to explain to anyone who works on the app that if they touch the variables.css file they have to clear cache and restart...

**Comment by kennedyrose** [comment]
Thanks! That'll have to work for now.

I'm having a hard time telling if this is a postcss, or babel-loader thing.

**Comment by jgubman** [comment]
Yeah, no clue, I'm guessing babel-loader

**Comment by khrome83** [comment]
we need this resolved as well. We use PostCSS `@import` to have different themes imported based on params during build. The lack of cache busting for these is painful.

**Comment by JosephScript** [comment]
Closing due to in-activity. Let me know if this is still an issue, as I haven't run into it myself.

**Comment by okhomenko** [comment]
@NukaPunk It's still an issue. Workaround suggested by @jgubman is ok for small projects, but for bigger projects it's not.
