### ISSUE TITLE
Template Literal Support: PostCSS Removes Comments

### ISSUE THREAD

**Issue by ryanfitzer** [giuseppeg/styled-jsx-plugin-postcss#20]
Regarding PR #2: I think this needs to be revisited. Currently, PostCSS removes all comments from the processed css:

> [PostCSS cleans values from comments by design.](https://github.com/postcss/postcss/issues/845#issuecomment-232306259)

So, since that comment is over a year before this PR, I'm a bit confused about the goal for this PR. I can understand why it fixed the `CssSyntaxError` issue, but it makes it so template literals are no longer able to be used ("dynamic css") as the value of a css property.

**Comment by giuseppeg** [comment]
good point, we should try to think of a better way to handle this. Maybe use custom properties as placeholders. @ryanfitzer do you have time to fix this?

**Comment by ryanfitzer** [comment]
Yeah. We rely pretty heavily on this and would love to help. We'll try to get a PR up this week.

Another issue we'd like to resolve is that the current file path being processed is not passed to PostCSS's `from` option. This is needed so PostCSS can use `.browserslistrc` and for plugins like `postcss-import`, among others.

This looks to be an issue with the `settings` that are passed in from `styled-jsx` (I'm assuming). The object has a `filename` property that is always `undefined` in our tests.

Could you help on any context you may have on getting the proper `filename` passed in a we can add that to our PR?

**Comment by giuseppeg** [comment]
The options are collected here https://github.com/zeit/styled-jsx/blob/master/src/babel.js#L230-L243 and assembled here https://github.com/zeit/styled-jsx/blob/master/src/_utils.js#L542-L551 

However for external styles they are collected here https://github.com/zeit/styled-jsx/blob/master/src/babel-external.js#L205-L209 and probably `fileInfo.filename` is missing. 

If you are exclusively using external styles from v3 you can actually have them in real `.css` files and use the webpack loader though. See https://github.com/zeit/styled-jsx#styles-in-regular-css-files If you use this you can process them with PostCSS before. Although it seems that you have interpolations and therefore using colocated styles, if we are discussing about that in this issue :) Can you open a separate issue for the `filename` one?

**Comment by ryanfitzer** [comment]
Thanks for the links to the specific files. I'll open a new ticket for the `filename` issue and add this context to it.

I'll update this thread with ideas for a solution to supporting template literals and then get a PR for it as soon as possible.

**Comment by ryanfitzer** [comment]
[Update} Figured out the `filename` issue and opened an [issue on `styled-jsx`](https://github.com/zeit/styled-jsx/issues/509). It's a simple typo. Hopefully the fix can be released relatively quickly :)

**Comment by lluisrojass** [comment]
Update on this: we are incorrect in assuming PostCSS strips comments globally, they apparently only strip comments between selectors. This still damages the flexibility of DX, but certainly not as detrimental as previously thought.

**Comment by JosephScript** [comment]
@ryanfitzer Looks like this can be closed?

**Comment by ryanfitzer** [comment]
I think so. I don't a way that `styled-jsx-plugin-postcss` could work around the issue.
