### ISSUE TITLE
VSCode CSS Linting

### ISSUE THREAD

**Issue by jkchuynh829** [giuseppeg/styled-jsx-plugin-postcss#21]
Any fix or workaround for this? 

![screen shot 2018-11-28 at 8 17 58 pm](https://user-images.githubusercontent.com/19925540/49199041-d9159580-f34a-11e8-975b-a9b977cb6acb.png)

**Comment by JosephScript** [comment]
I've had good luck using this extension: https://marketplace.visualstudio.com/items?itemName=blanu.vscode-styled-jsx

**Comment by jkchuynh829** [comment]
@NukaPunk Sorry, I should have been more clear. I'm using that extension and it works great. However,  nesting and `@media` rules still produce problems.

**Comment by JosephScript** [comment]
Unfortunately this isn't something we can fix with this plugin. But you should submit an issue on their repo: https://github.com/iFwu/vscode-styled-jsx

Maybe they can fix it or you can submit a PR to fix it!
