### ISSUE TITLE
addition to README.md

### ISSUE THREAD

**Issue by lluisrojass** [giuseppeg/styled-jsx-plugin-postcss#22]
It should probably be noted in the README that several `post-css` plugins interfere with this plugin's DX functionality. For starters `post-css` itself [strips comments from selectors by design](https://github.com/postcss/postcss/issues/1204) and the popular plugin [cssnano](https://github.com/cssnano/cssnano) opts you into comment stripping by default. Users looking to use cssnano in conjunction with DX should disable `disableComments` and also `disableEmpty` which would strip rules consisting of only commented out placeholders as such:

```javascript
div {
    /*%%styled-jsx-placeholder-1%%*/
}
```

I'd be happy to produce a PR if these additions are welcome

**Comment by JosephScript** [comment]
Feel free! We can review when you have a PR ready.
