### ISSUE TITLE
hangs in while loop

### ISSUE THREAD

**Issue by joonhocho** [giuseppeg/styled-jsx-plugin-postcss#32]
It never resolves and just hangs

**Comment by joonhocho** [comment]
https://github.com/giuseppeg/styled-jsx-plugin-postcss/blob/ec8a46a5909a63b1047111ff0fa7d1bf135f19a2/index.js#L17

**Comment by ademilter** [comment]
I'm having the same problem

**Comment by maikdiepenbroek** [comment]
Got the same issue

**Comment by baobabKoodaa** [comment]
This also affects several of my projects.

**Comment by giuseppeg** [comment]
Might be related to https://github.com/giuseppeg/styled-jsx-plugin-postcss/issues/31

**Comment by giuseppeg** [comment]
should be fixed in #35
