### ISSUE TITLE
Webpack build problems

### ISSUE THREAD

**Issue by smelted-code** [giuseppeg/styled-jsx-plugin-postcss#4]
This was seriously painful to find, but it looks easy to resolve.

Basically, if you use this with webpack (where it uses a config file), you get an issue pretty much identical to this:

https://github.com/davidtheclark/cosmiconfig/issues/77

It's because the configuration of webpack conflicts with the `argv` flag set in the version of `cosmicconfig` which `postcss-load-plugins` uses. 

One fix would be to allow developers to pass in options into `postcss-load-plugins` and I believe this is fixable.

In its current state, the plugin is unusable with the webpack `--config` flag.

**Comment by giuseppeg** [comment]
@smelted-code sounds good would you like to submit a PR? We can add a plugin option called `postCssLoadPlugins` I guess

**Comment by smelted-code** [comment]
I'll see if I can scrounge up an hour or two for a quick PR.

**Comment by huv1k** [comment]
@smelted-code Any update? I was trying to use it with webpack, but i couldnt load any plugins too :X
