### ISSUE TITLE
v3.0.0+ fails with tailwindcss

### ISSUE THREAD

**Issue by gauravkumar37** [giuseppeg/styled-jsx-plugin-postcss#40]
Tailwind css outputs some warning in stderr but they are not errors. So, after upgrading to v3, this plugin thinks there are errors and fails to compile.
Sample output generated by tailwindcss
```
warn - You have enabled experimental features: standardFontWeights, applyComplexClasses, extendedSpacingScale, defaultLineHeights, extendedFontSizeScale
warn - Experimental features are not covered by semver, may introduce breaking changes, and can change at any time.
```
For reproducing, we need to enable experimental features in tailwind config file.

Is there a way to only fail in case of errors but ignore warnings?

**Comment by giuseppeg** [comment]
yes we need to fix it to use the exit code, and when the code is 1. @gauravkumar37 Would you like to put up a pr for this? https://nodejs.org/api/child_process.html#child_process_child_process_spawnsync_command_args_options 

see `status` and `error`
