### ISSUE TITLE
Cache postcss renders

### ISSUE THREAD

**Issue by CallumJHays** [giuseppeg/styled-jsx-plugin-postcss#47]
Compilation takes too long. This might be because I'm using tailwindcss. That I can live with while I'm editing CSS because usually, I'm tweaking in the browser then copy-pasting. But when I'm just doing general edits it's really annoying to have to wait 15 seconds for the page to load every time. 

I'm wondering if the rendered css could be cached given the hash of the input css and the postcss config, so that reloads are instantaneous-ish.

**Comment by giuseppeg** [comment]
This should be fixed by https://github.com/giuseppeg/styled-jsx-plugin-postcss/pull/49
