### ISSUE TITLE
cssnext not working?

### ISSUE THREAD

**Issue by jabacchetta** [giuseppeg/styled-jsx-plugin-postcss#5]
Has anyone been able to get `postcss-cssnext` to work with this plugin?

Following [the next.js example](https://github.com/zeit/next.js/tree/master/examples/with-styled-jsx-plugins), I was able to setup `postcss-nested` with no problems. However, as soon as I swapped it out for cssnext, styles were completely lost.

**Comment by jabacchetta** [comment]
I've switched to using `precss` and so far it seems to be working. It looks like random things appear to break styles and I'm still trying to dig through everything to see what exactly is the cause.

Two scenarios where styles are breaking for me so far:

- When using Webstorm's language injection comments, and changing `// language=CSS` to `// language=SCSS` (but only when added to certain files — other files don't have this issue).

- When using next.js command `npm run start` — even though `npm run dev` appears to work.

**Comment by corysimmons** [comment]
postcss-cssnext seems to mostly work for me.

**Comment by pukapukan** [comment]
postcss-cssnext works for me as well

**Comment by jabacchetta** [comment]
Thanks!
