### ISSUE TITLE
Can't interpolate vars within parenthesis in styled-jsx-plugin-postcss. Works in styled-jsx

### ISSUE THREAD

**Issue by corysimmons** [giuseppeg/styled-jsx-plugin-postcss#8]
![image](https://user-images.githubusercontent.com/224636/34072040-568d7a8c-e24e-11e7-8452-55b6250e0791.png)

Not sure if this is cssnext's media query plugin, or styled-jsx.

**Comment by corysimmons** [comment]
Can't interpolate props into a _lot_ of PostCSS stuff...

Pretty much anywhere parenthesis are.

**Comment by corysimmons** [comment]
Reduced case.

```js
import React from 'react'

export default function foo () {
  const num = 2
  return (
    <div>
      <h1>interpolation test</h1>
      <style jsx>{`
        h1 {
          background: red;
          width: calc(100% / ${num});
        }
      `}</style>
    </div>
  )
}
```

...works with vanilla styled-jsx, but when I add `styled-jsx-plugin-postcss postcss-cssnext` and `postcss.config.js`:

```js
module.exports = (ctx) => ({
  plugins: {
    'postcss-cssnext': {},
  },
})
```

I get

```fish
Error in /Users/8888888/Desktop/ddsffff/pages/test.js?entry
Module build failed: Error: /Users/8888888/Desktop/ddsffff/pages/test.js?entry: Parse error on line 1:
100% /
------^
Expecting 'SUB', 'LPAREN', 'NESTED_CALC', 'NUMBER', 'CSS_VAR', 'LENGTH', 'ANGLE', 'TIME', 'FREQ', 'RES', 'EMS', 'EXS', 'CHS', 'REMS', 'VHS', 'VWS', 'VMINS', 'VMAXS', 'PERCENTAGE', got 'EOF'
    at Parser.parseError (/Users/8888888/Desktop/ddsffff/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:160:21)
    at Parser.parse (/Users/8888888/Desktop/ddsffff/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/parser.js:227:22)
    at /Users/8888888/Desktop/ddsffff/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/index.js:35:30
    at walk (/Users/8888888/Desktop/ddsffff/node_modules/postcss-value-parser/lib/walk.js:15:13)
    at ValueParser.walk (/Users/8888888/Desktop/ddsffff/node_modules/postcss-value-parser/lib/index.js:18:5)
    at exports.default (/Users/8888888/Desktop/ddsffff/node_modules/postcss-calc/node_modules/reduce-css-calc/dist/index.js:29:51)
    at transformValue (/Users/8888888/Desktop/ddsffff/node_modules/postcss-calc/dist/lib/transform.js:24:45)
    at exports.default (/Users/8888888/Desktop/ddsffff/node_modules/postcss-calc/dist/lib/transform.js:54:100)
    at /Users/8888888/Desktop/ddsffff/node_modules/postcss-calc/dist/index.js:28:52
    at /Users/8888888/Desktop/ddsffff/node_modules/postcss/lib/container.es6:109:26
```

I can confirm in various reduced cases you cannot interpolate a variable in-between parenthesis in styled-jsx-plugin-postcss.

You _can_ interpolate variables in-between parens (like `linear-gradient()`) in vanilla styled-jsx 2+ though.

**Comment by corysimmons** [comment]
Possibly the same problem https://github.com/omardelarosa/styled-jsx-plugin-stylus/pull/1/files aims to fix. I'll test locally and PR if it works.

**Comment by a-ignatov-parc** [comment]
Based on [this codepen](https://codepen.io/abietis/pen/rpZZmJ) there is no need for [this transformation](https://github.com/giuseppeg/styled-jsx-plugin-postcss/blob/master/index.js#L5-L8) 🤔

**Comment by a-ignatov-parc** [comment]
Found https://github.com/giuseppeg/styled-jsx-plugin-postcss/issues/3. 

It seams that we need to transform placeholders somehow 🤷‍♂️

**Comment by a-ignatov-parc** [comment]
Maybe transforming `%%styled-jsx-placeholder-0%%` to `var(_styled-jsx-placeholder-0_)` will work ok with PostCSS plugins.

**Comment by corysimmons** [comment]
Not sure. I opened a [lazy PR](https://github.com/giuseppeg/styled-jsx-plugin-postcss/pull/10) stealing your regex, and it seems to work in a fresh Next project with

```js
// package.json
{
  "scripts": {
    "dev": "next",
    "build": "next build",
    "start": "next start"
  },
  "dependencies": {
    "next": "^4.2.3",
    "postcss-cssnext": "^3.0.2",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "styled-jsx-plugin-postcss": "^0.1.2"
  }
}
```

```js
// postcss.config.js
module.exports = ctx => ({
  plugins: {
    'postcss-cssnext': {},
  },
})
```

```js
// pages/index.js
import React from 'react'

export default function foo () {
  const num = 3
  return (
    <div>
      <h1>interpolation test</h1>
      <style jsx>{`
        h1 {
          background: red;
          width: calc(100% / ${num});
        }
      `}</style>
    </div>
  )
}
```

![image](https://user-images.githubusercontent.com/224636/34991754-c0ce0e5e-fa98-11e7-984c-0037931ed6b5.png)

Hopefully @giuseppeg can help us from here and we can get this fixed. Really anxious to use props in combination with `calc()` and `nth-child()` :D

**Comment by tbaustin** [comment]
@corysimmons Did you figure out to fix this ? I am getting the same problem.

**Comment by corysimmons** [comment]
@tbaustin Sorry I forget this exact issue, I've been using styled-components + a CRA app, which I believe can do this. Eventually I realized I was over-engineering and just switched back to Sass and have been pretty happy with my efficiency.

**Comment by tbaustin** [comment]
I found using 
```
'postcss-cssnext': {
      features: {
        calc: false
      }
    },
```
in the `postcss.config.js` made it work. But Im sure that disables some other things I just have not ran into yet. That is the only fix I have found.

**Comment by corysimmons** [comment]
off-topic: postcss-calc is hit-or-miss and sometimes breaking so just always disable it anyway. 🤷‍♂️

**Comment by torresandres** [comment]
Any updates about this issue? I'm having this issue with the `repeat()` value for css grids and I didn't found any config to workaround this problem yet.

**Comment by JosephScript** [comment]
I believe this to be invalid now that we have moved to postcss-preset-env and off cssnext. But let me know if this is still an issue.

**Comment by muhajirdev** [comment]
I am still facing this issue. Any fix?

**Comment by hpachy** [comment]
same
